{{- if .Values.secrets.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventmesh.fullname" . }}-management-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventmesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ .Values.secrets.apiKeys | quote }}
{{- end }}
