apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventmesh.fullname" . }}-management-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eventmesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "eventmesh.name" . }}-management-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
